version = 0.1

[dev.deploy.parameters]
stack_name = "geovive-dev-agents"
region = "us-east-1"
s3_bucket = "geovive-deploy-666993265047-us-east-1"
s3_prefix = "agents/dev"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Env=dev"
tags = "project=geovive component=agents env=dev"
